local LSM = LibStub("LibSharedMedia-3.0")

LSM:Register("font", "American Captain", [[Interface\Addons\SharedMedia_Faiths\media\fonts\AmericanCaptain.ttf]])
LSM:Register("font", "Bebas Neue", [[Interface\Addons\SharedMedia_Faiths\media\fonts\BebasNeue-Regular.ttf]])
LSM:Register("font", "Big Noodle Titling", [[Interface\Addons\SharedMedia_Faiths\media\fonts\big_noodle_titling.ttf]])
LSM:Register("font", "Cocogoose", [[Interface\Addons\SharedMedia_Faiths\media\fonts\CocogoosePro-trial.ttf]])
LSM:Register("font", "College", [[Interface\Addons\SharedMedia_Faiths\media\fonts\college.ttf]])
LSM:Register("font", "Comfortaa", [[Interface\Addons\SharedMedia_Faiths\media\fonts\Comfortaa-Regular.ttf]])
LSM:Register("font", "Dashboard", [[Interface\Addons\SharedMedia_Faiths\media\fonts\Dashboard-Regular.ttf]])
LSM:Register("font", "Freshman", [[Interface\Addons\SharedMedia_Faiths\media\fonts\Freshman.ttf]])
LSM:Register("font", "Hack", [[Interface\Addons\SharedMedia_Faiths\media\fonts\Hack-Regular.ttf]])
LSM:Register("font", "Hack Bold", [[Interface\Addons\SharedMedia_Faiths\media\fonts\Hack-Bold.ttf]])
LSM:Register("font", "Janda Manatee", [[Interface\Addons\SharedMedia_Faiths\media\fonts\JandaManateeSolid.ttf]])
LSM:Register("font", "Jersey M54", [[Interface\Addons\SharedMedia_Faiths\media\fonts\JerseyM54.ttf]])
LSM:Register("font", "Keep Calm", [[Interface\Addons\SharedMedia_Faiths\media\fonts\KeepCalm-Medium.ttf]])
LSM:Register("font", "Kenyan Coffee", [[Interface\Addons\SharedMedia_Faiths\media\fonts\kenyancoffee.ttf]])
LSM:Register("font", "Kenyan Coffee", [[Interface\Addons\SharedMedia_Faiths\media\fonts\kenyancoffee-bd.ttf]])
LSM:Register("font", "Ketsana", [[Interface\Addons\SharedMedia_Faiths\media\fonts\Ketsana-Regular-PU.ttf]])
LSM:Register("font", "Letters for Learners", [[Interface\Addons\SharedMedia_Faiths\media\fonts\LettersforLearners.ttf]])
LSM:Register("font", "Moon Get!", [[Interface\Addons\SharedMedia_Faiths\media\fonts\moon_get-Heavy.ttf]])
LSM:Register("font", "Simplicity", [[Interface\Addons\SharedMedia_Faiths\media\fonts\simplicity.ttf]])
LSM:Register("font", "The Bold Font", [[Interface\Addons\SharedMedia_Faiths\media\fonts\theboldfont.ttf]])
LSM:Register("font", "VCR OSD", [[Interface\Addons\SharedMedia_Faiths\media\fonts\VCR_OSD_MONO_1.001.ttf]])