local LSM = LibStub("LibSharedMedia-3.0")

LSM:Register("font", "American Captain", [[Interface\Addons\SharedMedia_Faiths\media\fonts\AmericanCaptain.ttf]])
LSM:Register("font", "Aurora", [[Interface\Addons\SharedMedia_Faiths\media\fonts\Aurora.ttf]])
LSM:Register("font", "Bavaria", [[Interface\Addons\SharedMedia_Faiths\media\fonts\Bavaria.ttf]])
LSM:Register("font", "Bebas Neue", [[Interface\Addons\SharedMedia_Faiths\media\fonts\BebasNeue-Regular.ttf]])
LSM:Register("font", "Big Noodle Titling", [[Interface\Addons\SharedMedia_Faiths\media\fonts\big_noodle_titling.ttf]])
LSM:Register("font", "Cocogoose", [[Interface\Addons\SharedMedia_Faiths\media\fonts\CocogoosePro-trial.ttf]])
LSM:Register("font", "College", [[Interface\Addons\SharedMedia_Faiths\media\fonts\college.ttf]])
LSM:Register("font", "Comfortaa", [[Interface\Addons\SharedMedia_Faiths\media\fonts\Comfortaa-Regular.ttf]])
LSM:Register("font", "Dashboard", [[Interface\Addons\SharedMedia_Faiths\media\fonts\Dashboard-Regular.ttf]])
LSM:Register("font", "Freshman", [[Interface\Addons\SharedMedia_Faiths\media\fonts\Freshman.ttf]])
LSM:Register("font", "Frucade", [[Interface\Addons\SharedMedia_Faiths\media\fonts\Frucade.ttf]])
LSM:Register("font", "Frucade Medium", [[Interface\Addons\SharedMedia_Faiths\media\fonts\FrucadeMedium.ttf]])
LSM:Register("font", "GoodTimes", [[Interface\Addons\SharedMedia_Faiths\media\fonts\GoodTimes.ttf]])
LSM:Register("font", "Gros", [[Interface\Addons\SharedMedia_Faiths\media\fonts\Gros.ttf]])
LSM:Register("font", "Hack", [[Interface\Addons\SharedMedia_Faiths\media\fonts\Hack-Regular.ttf]])
LSM:Register("font", "Janda Manatee", [[Interface\Addons\SharedMedia_Faiths\media\fonts\JandaManateeSolid.ttf]])
LSM:Register("font", "Jersey M54", [[Interface\Addons\SharedMedia_Faiths\media\fonts\JerseyM54.ttf]])
LSM:Register("font", "Keep Calm", [[Interface\Addons\SharedMedia_Faiths\media\fonts\KeepCalm-Medium.ttf]])
LSM:Register("font", "Kenyan Coffee", [[Interface\Addons\SharedMedia_Faiths\media\fonts\kenyancoffee.ttf]])
LSM:Register("font", "Ketsana", [[Interface\Addons\SharedMedia_Faiths\media\fonts\Ketsana-Regular-PU.ttf]])
LSM:Register("font", "Letters for Learners", [[Interface\Addons\SharedMedia_Faiths\media\fonts\LettersforLearners.ttf]])
LSM:Register("font", "Monofonto", [[Interface\Addons\SharedMedia_Faiths\media\fonts\Monofonto.ttf]])
LSM:Register("font", "Moon Get!", [[Interface\Addons\SharedMedia_Faiths\media\fonts\moon_get-Heavy.ttf]])
LSM:Register("font", "Munica", [[Interface\Addons\SharedMedia_Faiths\media\fonts\Munica.ttf]])
LSM:Register("font", "PrintClearly", [[Interface\Addons\SharedMedia_Faiths\media\fonts\PrintClearly.ttf]])
LSM:Register("font", "Prototype", [[Interface\Addons\SharedMedia_Faiths\media\fonts\Prototype.ttf]])
LSM:Register("font", "Semplice", [[Interface\Addons\SharedMedia_Faiths\media\fonts\Semplice.ttf]])
LSM:Register("font", "Simplicity", [[Interface\Addons\SharedMedia_Faiths\media\fonts\simplicity.ttf]])
LSM:Register("font", "SimplyRounded", [[Interface\Addons\SharedMedia_Faiths\media\fonts\SimplyRounded.ttf]])
LSM:Register("font", "The Bold Font", [[Interface\Addons\SharedMedia_Faiths\media\fonts\theboldfont.ttf]])
LSM:Register("font", "WhiteRabbit", [[Interface\Addons\SharedMedia_Faiths\media\fonts\WhiteRabbit.ttf]])