local LSM = LibStub("LibSharedMedia-3.0")

-- PvE Content

LSM:Register("sound", "|cFFF2B6B6PvE: Crowd Controlled", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\crowd_controlled.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Dont Move", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\dont_move.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Group 6", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\group_6.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Add Spawned", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\add_spawned.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Collect", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\collect.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Get Out", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\get_out.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Stand Still", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\stand_still.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Stop Casting", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\stop_casting.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Switch Target", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\switch_target.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Stop Moving", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\stop_moving.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Group 2", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\group_2.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Target Buffed", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\target_buffed.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Personal CD", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\personal_cd.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Group 5", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\group_5.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Target Debuffed", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\target_debuffed.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Run Out", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\run_out.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Target Immune", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\target_immune.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Healing CD", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\healing_cd.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Stack Up", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\stack_up.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: High Stacks", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\high_stacks.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: High Energy", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\high_energy.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Beam Incoming", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\beam_incoming.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Decreased Damage", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\decreased_damage.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Mines", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\mines.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Spellsteal Buff", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\spellsteal_buff.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Group 3", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\group_3.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Pre-Potion", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\pre-potion.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Adds Spawned", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\adds_spawned.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Spread Out", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\spread_out.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Heroism", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\heroism.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Increased Damage", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\increased_damge.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Linked Player", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\linked_to_player.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Look Away", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\look_away.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Interrupt", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\interrupt.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Move Skull", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\move_to_skull.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Avoid Ability", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\avoid_ability.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Move Square", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\move_to_square.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Move X", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\move_to_x.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Linked Players", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\linked_to_players.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: More Star", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\move_to_star.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Knockback Incoming", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\knockback_incoming.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Dispel Ally", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\dispel_ally.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Move Circle", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\move_to_circle.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Group 4", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\group_4.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Purge Boss", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\purge_boss.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Bait Ability", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\bait_ability.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Hide", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\hide.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Taunt Boss", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\taunt_boss.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Move Diamond", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\move_to_diamond.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Crowd Control", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\crowd_control.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Turn Away", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\turn_away.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Transition", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\transition.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Dodge Ability", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\dodge_ability.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Taunt Swap", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\taunt_swap.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Immunity", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\immunity.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Group 1", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\group_1.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Purge Target", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\purge_target.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Clear Stacks", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\clear_stacks.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Soak Ability", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\soak_ability.ogg]])
LSM:Register("sound", "|cFFF2B6B6PvE: Second Potion", [[Interface\Addons\SharedMedia_Faiths\media\sounds\pve\generic\second_potion.ogg]])